在程序中，不应该出现因为一个不算致命的问题，就导致整个系统崩溃的情况。因此，java 设计者，提供了异常处理机制来解决该问题。

如果程序员，认为一段代码可能出现异常/问题，可以使用 try-catch 异常处理机制来解决，从而保证程序的健壮性。

如果进行异常处理，那么即使出现了异常，程序可以继续执行。

## 12.3 异常介绍

Java语言中，将程序执行中发生的不正常情况称为”异常“。

> 注意：开发过程中的语法错误和逻辑错误不是异常。

执行过程中所发生的异常时间可分为两大类：

- Error：Java虚拟机无法解决的严重问题，Error是严重错误，程序会崩溃。如JVM系统内部错误、资源耗尽（StackOverflowError、OOM(out of memory))。
- Exception：其它因编程错误或偶然的外在因素导致的一般性问题，可以使用针对性的代码继续处理。Exception分为两大类：运行时异常和编译时异常。如空指针访问、试图读取不存在的文件、网络连接中断等。

---

异常体系图一览：

![image-20220703220634434](https://cdn.jsdelivr.net/gh/Ninnaneve/my_pic@main/image-20220703220634434.png)

> 虚线表示实现接口，实线表示继承。

小结：

1. 异常分为两大类，运行时异常和编译时异常。
2. 运行时异常，编译器检查不出来。一般是指编程时的逻辑错误，是程序员应该避免出现的异常。
3. 对于运行时异常，可以不做处理，因为这类异常很普遍，若全处理可能会对程序的可读性和运行效率产生影响。
4. 编译时异常，是编译器要求必须处置的异常。



## 12.5 常见的运行时异常 

常见的运行时异常包括： 

1) NullPointerException 空指针异常 

   当应用程序试图在需要对象的地方使用 null 时，抛出该异常。

2) ArithmeticException 数学运算异常

   当出现异常的运算条件时，抛出此异常。

3) ArrayIndexOutOfBoundsException 数组下标越界异常

   用非法索引访问数组时抛出的异常。如果索引为负或大于等于数组大小，则该索引为非法索引。

4) ClassCastException 类型转换异常

   当试图将对象强制转换为不是实例的子类时，抛出该异常。

5) NumberFormatException 数字格式不正确异常

   当应用程序试图将字符串转换成一种数值类型，但该字符串不能转换为适当格式时，抛出该异常 => 使用异常我们可以确保输入是满足条件数字。

P.S. 把字符串转换为整数：`Interger.parseInt()`，也用于异常处理时判断输入是否为整数



## 12.6 编译异常

编译时异常是指在编译期间，就必须处理的异常，否则代码不能编译通过。

常见的编译异常：

- SQLException：操作数据库时，查询表可能发生异常
- IOException：操作文件时发生的异常
- FileNotFoundException：当操作一个不存在的文件时，发生异常
- ClassNotFoundException：加载类，若该类不存在，则发生异常
- EOFException：操作文件，到文件末尾，发生异常
- IllegalArgumentException：参数异常



## 12.8 异常处理

异常处理就是当异常发生时，对异常的处理方式。

异常处理的方式：

- try-catch-finally：程序员在代码中捕获发生的异常，自行处理

  快捷方式：将该代码块选中 -> 快捷键 ctrl + alt + t -> 生成 try-catch代码块

  > 补充：e.getMessage()：获取异常信息

  示意图：

  ![image-20220703221838059](https://cdn.jsdelivr.net/gh/Ninnaneve/my_pic@main/image-20220703221838059.png)

- throws：将发生的异常抛出，交给调用者（方法）来处理，最顶级的处理中就是JVM

  在定义方法时，尾部会默认定义`throws Exception`

  示意图：

  ![image-20220704193629410](https://cdn.jsdelivr.net/gh/Ninnaneve/my_pic@main/image-20220704193629410.png)



## 12.9 try-catch 异常处理

Java提供try和catch块来处理异常。try块用于包含可能出错的代码，catch块用于处理try块发生的异常。可以根据需要在程序中有多个try...catch块。

基本语法：

```java
try{
    // 可疑代码
    // 将异常生成对应的异常对象，传递给catch块
} catch(异常){
    // 对异常的处理
} finally{ 
    // 如果没有finally，语法是可以通过的
}
```



----

注意事项：

- 如果try块中异常发生了，则异常发生后的代码不会执行，直接进入catch块，catch块执行完毕后，后面的语句会正常运行，因为异常已经被处理了
- 如果异常没有发生，则顺序执行try代码块，不会进入到catch块
- 如果希望不管是否发生异常，都执行某段代码（如关闭连接、释放资源），则使用finally
- 可以有多个catch语句，捕获不同的异常（进行不同的业务处理），要求父类异常在后，子类异常在前。如果发生异常，只会匹配一个catch
- 可以进行try-finally配合使用，这种用法相当于没有捕获异常，因此程序会直接崩掉/退出。应用场景为：执行一段代码，不管是否发生异常，都必须执行某个业务逻辑。



P.S. 容易出错的点

```java
public static int method(){
    int i = 1;
    try{}
    catch(){
        ...;
        return i++; // i++会执行，但不会返回值
    } finally{
        return ++i; // 因为必须执行，所以最终输出的是++i的值
    }
}

// main，输出结果4
System.out.println(method());
```

另一种情况：

```java
public static int method(){
    int i = 1;
    try{}
    catch(){
        ...;
        return i++; // i++会执行，并被系统保存到一个临时变量temp中，最终返回的也是2
    } finally{
        ++i;
        System.out.println("i=" + i); // i此时为3，并且该句先打印出来
    }
}

// main，输出结果i=3 2
System.out.println(method());
```

以及，各个语句块中定义的变量不能在代码块外使用。



## 12.10 throws 异常处理 

基本介绍：

- 如果一个方法中的语句执行时可能生成某种异常，但是并不能确定如何处理这种异常，则此方法应显示地声明抛出异常，表明该方法将不对这些异常进行处理，而由该方法的调用者负责处理
- 在方法声明中用throws语句可以声明抛出异常的列表，即可以抛出多个异常
- throws后面的异常类型可以是方法中产生的异常类型，也可以是它的父类

----

注意事项和使用细节：

- 对于编译异常，程序中必须处理
- 对于运行时异常，程序中如果没有处理，默认就是throws的方式处理

例如，

```java
/*
这里调用 f3() 报错：
1. 因为 f3() 方法抛出的是一个编译异常。这时，就要 f1() 必须处理这个编译异常。
3. 在 f1() 中，要么 try-catch-finally，或者继续 throws 这个编译异常
*/
public static void f1() throws FileNotFoundException {
	f3(); // 抛出异常
}
public static void f3() throws FileNotFoundException {
	FileInputStream fis = new FileInputStream("d://aa.txt");
}

/*
在 f4()中调用方法 f5() 是 OK 的
原因是 f5() 抛出的是运行异常，在 java 中，并不要求程序员显示处理，因为有默认处理机制。
*/
public static void f4() {
	f5();
}
public static void f5() throws ArithmeticException {
}
```

- 在throws过程中，如果有方法try-catch，就相当于异常处理，可以不必throws
- 子类重写父类方法时，对抛出异常的规定：子类重写的方法，所抛出的异常类型要么和父类抛出的异常一致，要么为父类抛出的异常的类型的子类型（类似重写的返回类型要求）



## 12.11 自定义异常 

当程序中出现了某些”错误“，但该错误信息并没有在Throwable子类中描述处理，这个时候可以自己设计异常类，用于描述该错误信息。

如何自定义异常：

- 定义类：自定义异常类名（程序员自己写），继承Exception（属于编译异常）或RuntimeException（属于运行异常）
- 一般情况下，我们自定义异常是继承 RuntimeException，即把自定义异常做成运行时异常，好处是我们可以使用默认的处理机制，比较方便

例如，要求范围在 18 – 120 之间，否则抛出一个自定义

```java
public class CustomException {
public static void main(String[] args) /*throws AgeException*/ {
        int age = 180;
        //要求范围在 18 – 120 之间，否则抛出一个自定义异常
        if(!(age >= 18 && age <= 120)) {
            //即通过构造器，设置信息
            throw new AgeException("年龄需要在 18~120 之间");
        }
    	System.out.println("你的年龄范围正确.");
    }
}
//自定义一个异常
class AgeException extends RuntimeException {
    public AgeException(String message) {//构造器
        super(message);
    }
}
```



## 12.12 throw 和 throws 的区别

![image-20220704200614346](https://cdn.jsdelivr.net/gh/Ninnaneve/my_pic@main/image-20220704200614346.png)

可以参考上例代码。

注意：若try语句块中有throw，且有finally语句块，会先输出throw之前语句，再输出finally语句块，最后输出throw。